sudo: false
language: php
php:
  - "7"
  - "5.6"
  - "5.5"
  - "5.4"
  - "5.3"
script:
  - find . -name '*.php' -print0 | xargs -0 -L 1 -P 8 php -l
notifications:
  irc:
    channels:
      - "chat.freenode.net##krinkle"
